task:
  freebsd_instance:
    cpu: 2
    memory: 8G
    matrix:
      # image: freebsd-12-2-release-amd64
      - image: freebsd-13-0-release-amd64

  env:
    USER: 1000
    CIRRUS_CLONE_DEPTH: 1
    GITHUB_TOKEN: ENCRYPTED[22b81c0d39004cef726f2adcff6027fb4ef1dba049a10d8ffd94fc312cbaade14f0b3d33377856c2a4d14bc36846f453]
    
  auto_cancellation: false
  stateful: false
  timeout_in: 60m
  # only_if: $CIRRUS_TAG !=~ 'continuous.*'
  # Do not build tags, only commits
  only_if: $CIRRUS_TAG !=~ '..*'

  env:
    matrix:
      arch: 'amd64'

  Environment_script:
    - env
    - kldload zfs.ko
    - kldload tmpfs.ko || true
    - kldload nullfs.ko || true
    - kldload geom_uzip.ko || true
    - kldload linux64 || true
    - kldload fdescfs || true
    - kldload linprocfs || true
    - pkg install -y pkg
    
  Build_script:
    - mkdir -p /compat
    - mount -t tmpfs tmpfs /compat
    - mkdir -p /compat/debian
    - mount -t tmpfs tmpfs /tmp
    - echo "Europe/Berlin" > /var/db/zoneinfo # FIXME: Find a way not to hardcode this
    - sh -ex ./prepare-debian-userland.sh chroot create
    - umount -f /compat/*/tmp || true
    - umount -f /compat/*/dev/shm || true
    - umount -f /compat/*/dev/fd || true
    - umount -f /compat/*/dev || true
    - umount -f /compat/*/sys || true
    - umount -f /compat/*/proc || true
    - makefs -o 'label=debian' /tmp/debian.ufs /compat/debian
    - mkuzip -A zstd -C 15 -d -s 262144 -o /tmp/debian.img /tmp/debian.ufs
    - readlink -f /tmp/debian.img
    - ls -lh /tmp/debian.img
    
  Upload_script:
    - export VER=$(uname -r | cut -d "-" -f 1) # No way to pass on from Build_script to Upload_script?
    - export RELEASE_NAME="bullseye"
    - case "$CIRRUS_BRANCH" in *pull/*) echo skipping since PR ;; * ) wget -c -q https://github.com/tcnksm/ghr/files/5247714/ghr.zip ; unzip ghr.zip ; ./ghr -prerelease -delete -t "${GITHUB_TOKEN}" -u "${CIRRUS_REPO_OWNER}" -r "${CIRRUS_REPO_NAME}" -b "This is an experimental __UNTESTED__ build for developers." -c "${CIRRUS_CHANGE_IN_REPO}" "$RELEASE_NAME" /tmp/debian.img ; esac
